# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fastlane"

plugins_path = 'fastlane/Pluginfile'
eval_gemfile(plugins_path) if File.exist?(plugins_path)
