default_platform(:android)

platform :android do
    lane :adhoc do
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            groups: "developer",
            firebase_cli_path: `which firebase`.strip(),
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            apk_path: ENV["APK_PATH"],
            release_notes: "test",
            debug: true
        )
        slack(
            message: "ベータ版が配信されました\nhttps://appdistribution.firebase.dev/app_distro/projects",
            slack_url: ENV["SLACK_URL"]
        )
    end
end

platform :ios do

    desc "Create certs"
    lane :create_certs do

        create_keychain(
            default_keychain: true,
            name: "mykeychain",
            password: ENV["KEYCHAIN_PASSWORD"],
            unlock: true,
            timeout: 180
        )

        match(
            readonly: false,
            type: "adhoc",
            keychain_name: "mykeychain",
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            verbose: true
        )

        slack(
            message: "Init certificate complete.",
            slack_url: ENV["SLACK_URL"]
        )
    end

end
