name: Test, Build, and Release ActionSample

on:
  release: 
    types: [published]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - name: Run EditMode and PlayMode Tests
        uses: game-ci/unity-test-runner@main
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: artifacts

  buildAndroidDev:
    name: Build for Android(Dev)
    runs-on: ubuntu-latest
    needs: test
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Android
          restore-keys: Library-
      - name: Free Disk Space for Android
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Build Unity Project
        uses: game-ci/unity-builder@main
        with:
          targetPlatform: Android
          buildsPath: builds         
          androidAppBundle: false
          # androidKeystoreName: urbantheory.keystore
          # androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          # androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          # androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          # androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      - name: List BuildDir
        run: |
          apt update
          apt install -y tree
          ls -l builds/Android
          tree builds/Android
      - name: Pilot
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: android-adhoc
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}

           

  # buildiOSDev:
  #   name: Build for iOS(Dev)
  #   runs-on: ubuntu-latest
  #   needs: test
  #   env:
  #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #     UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #       with:
  #         lfs: true
  #     - name: Cache Library
  #       uses: actions/cache@v2
  #       with:
  #         path: Library
  #         key: Library-iOS
  #         restore-keys: Library-
  #     - name: Build Unity Project
  #       uses: game-ci/unity-builder@main
  #       with:
  #         targetPlatform: iOS
  #         buildsPath: builds         
  #     - name: List BuildDir
  #       run: ls -l builds
